### ISSUE TITLE
Setting up Volta Solar Battery fails 

### ISSUE THREAD

**Issue by stoubygronkjaer** [AThomsen/home-assistant_xolta_battery#1] opened 2023-10-15 07:40 UTC
I've set up Home Assistant with Xolta Battery Authentication, but adding Xolta Solar Battery integration fails at login to app.xolta.com.
The account and password is verified at web login.
Firewall rules are checked, nothing blocked.
Seems like the Xolta Battery Authentication use app.xolta.com and has a time-out of 5 secs. which should be sufficient.
Any ideas where to look?
-----
From Xolta Bettery Authentication log:
_Xolta: requesting site
Start Request
Login form
XoltaBattAuthenticator Error: TimeoutError: Timeout exceeded while waiting for event Symbol(NetworkManager.Response)
Return: {"status":"500","message":"TimeoutError: Timeout exceeded while waiting for event Symbol(NetworkManager.Response)","duration":7.576}_
 
From Home Assistant log:
_Traceback (most recent call last):
  File "/config/custom_components/xolta_batt/xolta_api.py", line 94, in test_authentication
    await self.refresh_tokens()
  File "/config/custom_components/xolta_batt/xolta_api.py", line 111, in refresh_tokens
    await self.login()
  File "/config/custom_components/xolta_batt/xolta_api.py", line 89, in login
    raise exceptions.ConfigEntryNotReady from ex
homeassistant.exceptions.ConfigEntryNotReady: Error logging in. Status: 500: TimeoutError: Timeout exceeded while waiting for event Symbol(NetworkManager.Response)
2023-10-15 09:07:29.264 ERROR (MainThread) [custom_components.xolta_batt.xolta_api] Error calling Xolta authentication add-on: Error logging in. Status: 500: TimeoutError: Timeout exceeded while waiting for event Symbol(NetworkManager.Response) 
Traceback (most recent call last):
  File "/config/custom_components/xolta_batt/xolta_api.py", line 80, in login
    raise Exception(
Exception: Error logging in. Status: 500: TimeoutError: Timeout exceeded while waiting for event Symbol(NetworkManager.Response)
2023-10-15 09:07:29.264 ERROR (MainThread) [custom_components.xolta_batt.xolta_api] Unable to fetch login token from Xolta API. Error logging in. Status: 500: TimeoutError: Timeout exceeded while waiting for event Symbol(NetworkManager.Response)
2023-10-15 09:07:29.264 ERROR (MainThread) [custom_components.xolta_batt.xolta_api] API Authentication exception: Error logging in. Status: 500: TimeoutError: Timeout exceeded while waiting for event Symbol(NetworkManager.Response)
Traceback (most recent call last):
  File "/config/custom_components/xolta_batt/xolta_api.py", line 80, in login
    raise Exception(
Exception: Error logging in. Status: 500: TimeoutError: Timeout exceeded while waiting for event Symbol(NetworkManager.Response)__

**Comment by AThomsen** [comment] 2023-10-15 08:29
Not sure what is causing this. Timeout is currently 5s but perhaps it should be increased. 

What HW are you using? How much time does the login take in a regular browser when you hit the "Log på" button?

**Comment by stoubygronkjaer** [comment] 2023-10-15 08:33
I'm using Home Assistant appliance on Vmware ESXi.
Ordinary login in browser is 3 - 4 secs.

**Comment by RasmusOtharKirketerp** [comment] 2023-10-15 08:37
Has it worked before in your setup or is it first time setup?
It still runs on my rpi without any errors

**Comment by AThomsen** [comment] 2023-10-15 08:50
I have raised timeout to 10s. and released as version 1.1.1.1

Please check if that makes any difference.

https://github.com/AThomsen/home-assistant_xolta_battery_authentication-addon/commit/890b1e09b65aa43bf19c0c988881566d053e6432

**Comment by stoubygronkjaer** [comment] 2023-10-15 09:09
Installed the update - restarted Home Assistant and tried to add the integration. Login failed again.
Log from Xolta Battery Authentication:
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Running on http://0.0.0.0:8000
Xolta: requesting site
Start Request
Login form
XoltaBattAuthenticator Error: TimeoutError: Timeout exceeded while waiting for event Symbol(NetworkManager.Response)
Return: {"status":"500","message":"TimeoutError: Timeout exceeded while waiting for event Symbol(NetworkManager.Response)","duration":16.056}

I had a first-time setup of Home Assistant (like the current) which got a bit messy. I deleted the appliance and created this new one from scratch.

I aim to use it for managing the house battery not to deliver power when charging my EV. I want to use a signal from Zaptec Go charger to initiate a script setting the Xolta battery in idle-mode.
When the Zaptec Go signals "not charging", a script changes the Xolta battery back to running-mode.

**Comment by AThomsen** [comment] 2023-10-15 09:28
Ok. Then I can't think of what the problem is.

The next thing to do is running the auth-service locally in VScode with `headless: 'false',` to see exactly what's going in this case. Mind giving that a try?

**Comment by AThomsen** [comment] 2023-10-15 09:29
An bwt, the this integration cannot control the battery in any way. It only provides data from the sensors (power flow etc.).

**Comment by stoubygronkjaer** [comment] 2023-10-15 10:11
I'll give it a go, running the code locally. although I have no idea how :)
Control of the battery is done via api commands. I know what to do, but needs to figure out how to do it from Home Assistant.

**Comment by AThomsen** [comment] 2023-10-15 20:15
Ok. Let me know if you need any help 😊

**Comment by stoubygronkjaer** [comment] 2023-10-16 14:48
I have to admit my lack of skills :( so yes, I need help to do the test in question.
I can find the script files for Xolta Solar Battery, but not for the authenticate module.

**Comment by AThomsen** [comment] 2023-10-16 15:18
It's in another repo: https://github.com/AThomsen/home-assistant_xolta_battery_authentication-addon

You'll need a working NodeJS environment: https://learn.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-beginners-tutorial

Then open the 'App' folder in the repo in VSCode.
In the terminal in VSCode, type `npm install` to install the needed packages.
Open `server.js` and hit F5 and hopefully you'll get a `Running on http://0.0.0.0:8000`.

You can then call the service and get a response with an access token : 
`curl -X POST http://localhost:8000/login -H 'Content-Type: application/json' -d '{"username":"login-mail-address-goes-here","password":"and-your-password-here"}' `

If it works, then the error is related to the environment running HA. Not sure what it would be though...

Hopefully it won't work and then it must be related to something about your specific user.

**Comment by stoubygronkjaer** [comment] 2023-10-16 17:40
Ok, thanks. That was actually the help I needed. I managed to get it running and here goes the result:

/opt/homebrew/bin/node ./app/server.js
Running on http://0.0.0.0:8000

lsg@StoubyMBP ~ % curl -X POST http://localhost:8000/login -H 'Content-Type: application/json' -d '{"username":"<userid>","password":"<passwd>"}'

Xolta: requesting site
XoltaBattAuthenticator Error: Error: Failed to launch the browser process! spawn /usr/bin/chromium ENOENT


TROUBLESHOOTING: https://pptr.dev/troubleshooting

Return: {"status":"500","message":"Error: Failed to launch the browser process! spawn /usr/bin/chromium ENOENT\n\n\nTROUBLESHOOTING: https://pptr.dev/troubleshooting\n","duration":0.014}

**Comment by AThomsen** [comment] 2023-10-17 08:27
That because it expects to find the Chromium browser in `/usr/bin/chromium` (Linux).

You can try using puppeteer(which comes with Chrome bundled) instead of puppeteer-core:

nstall puppeteer - run from a terminal while in the `app` directory:
~~~ 
npm install puppeteer
~~~ 

Change the first line in `xolta_auth.js` to
~~~ts
const puppeteer = require('puppeteer');
~~~ 
and use this to initialize the browser, replacing the existing code
~~~
        const browser = await puppeteer.launch({
            headless: 'false',   // <-- disable headless so the browser window is shown. For debugging.
            // executablePath: '/usr/bin/chromium',     <-- not needed as the bundled browser is used.
            args: ['--no-sandbox', '--disable-gpu', '--disable-dev-shm-usage'],
        });
~~~

**Comment by stoubygronkjaer** [comment] 2023-10-17 13:59
I installed puppeteer and made the code changes.
Runned curl and got this result in the debug window:

/opt/homebrew/bin/node ./app/server.js
Running on http://0.0.0.0:8000
Xolta: requesting site
Start Request
Login form
XoltaBattAuthenticator Error: TimeoutError: Timeout exceeded while waiting for event Symbol(NetworkManager.Response)
Return: {"status":"500","message":"TimeoutError: Timeout exceeded while waiting for event Symbol(NetworkManager.Response)","duration":12.747}

**Comment by AThomsen** [comment] 2023-10-17 14:08
That's great - you are able to recreate the error!

If you managed to disable "headless", you should see an actual browser window and in there you can see what happens. Perhaps set breakpoints in the code to slow it down.

**Comment by stoubygronkjaer** [comment] 2023-10-17 14:22
I have set a breakpoint in this line
const submitButton = await page.waitForSelector('#next', { timeout });
Waiting >10 secs before continuing results in success and the token is returned.

**Comment by AThomsen** [comment] 2023-10-17 14:25
So you raised the timeout even higher?

**Comment by stoubygronkjaer** [comment] 2023-10-17 14:33
No, the timeout is kept at 10 secs.
The delay is manually by me, waiting about 10 - 12 secs before I let the code continue from the breakpoint.

**Comment by AThomsen** [comment] 2023-10-17 14:34
What happens if you set the timeout timeout to 30s (something high) and run it without breakpoint?

**Comment by stoubygronkjaer** [comment] 2023-10-17 14:38
<img width="1423" alt="image" src="https://github.com/AThomsen/home-assistant_xolta_battery/assets/137001666/d9f6e2ea-45ab-4bd8-a1bb-b1cce39e2f1a">
Breakpoint set and waiting 10 - 12 secs before continuing and the curl request returns a token.

**Comment by AThomsen** [comment] 2023-10-17 14:44
Yes, but what happens if you increase https://github.com/AThomsen/home-assistant_xolta_battery_authentication-addon/blob/890b1e09b65aa43bf19c0c988881566d053e6432/xolta-batt-auth/app/xolta_auth.js#L4

**Comment by stoubygronkjaer** [comment] 2023-10-17 14:45
Set timeout to 30 secs and no breakpoint. The request got error 500.

**Comment by AThomsen** [comment] 2023-10-17 14:50
What happens if you insert `time.sleep(1)` on line 32 (according to the screenshot above)?

**Comment by AThomsen** [comment] 2023-10-17 14:57
Try to add a sleep method:

Insert on line ~3:
~~~
function sleep(ms) {
    return new Promise((resolve) => setInterval(resolve, ms));
}
~~~

and then call it after the line `const submitButton = await page.waitForSelector('#next', { timeout });`, add:
~~~
await sleep(1000);
~~~

**Comment by stoubygronkjaer** [comment] 2023-10-17 15:00
Did the trick. I got a http 200 and a token in the response.

**Comment by stoubygronkjaer** [comment] 2023-10-17 15:03
Tested different wait times.
100ms failed
200ms success
250ms success

**Comment by AThomsen** [comment] 2023-10-17 15:21
Ok. I've added a 500ms delay and released it as 1.1.2. Please test it in HA :-)

**Comment by stoubygronkjaer** [comment] 2023-10-17 16:36
Brilliant. Now I can add my battery. Thanks a lot.
I also have learned a thing or two.

**Comment by AThomsen** [comment] 2023-10-17 17:12
Good to hear :-)

**Closed by AThomsen** 2023-10-17 17:12 UTC
